// <auto-generated />
using System;
using KROTraining.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KROTraining.Migrations
{
    [DbContext(typeof(KroTrainingContext))]
    [Migration("20260923214447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KROTraining.Models.Administrador", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("UsuarioId");

                    b.ToTable("ADMINISTRADOR", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.AsignacionRutina", b =>
                {
                    b.Property<int>("AsignacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("asignacion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsignacionId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<int>("EntrenadorId")
                        .HasColumnType("int")
                        .HasColumnName("entrenador_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("ACTIVA")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_asignacion")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("RutinaId")
                        .HasColumnType("int")
                        .HasColumnName("rutina_id");

                    b.HasKey("AsignacionId");

                    b.HasIndex("RutinaId");

                    b.HasIndex(new[] { "ClienteId" }, "IX_ASIGNACION_CLIENTE");

                    b.HasIndex(new[] { "EntrenadorId" }, "IX_ASIGNACION_ENTRENADOR");

                    b.ToTable("ASIGNACION_RUTINA", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.Asistencium", b =>
                {
                    b.Property<int>("AsistenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("asistencia_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsistenciaId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time")
                        .HasColumnName("hora");

                    b.HasKey("AsistenciaId");

                    b.HasIndex(new[] { "ClienteId", "Fecha" }, "IX_ASISTENCIA_CLIENTE_FECHA");

                    b.HasIndex(new[] { "ClienteId", "Fecha" }, "UQ_ASISTENCIA_CLIENTE_FECHA")
                        .IsUnique();

                    b.ToTable("ASISTENCIA", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.Auditorium", b =>
                {
                    b.Property<int>("AuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("auditoria_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditoriaId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("accion");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detalle");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("AuditoriaId");

                    b.HasIndex(new[] { "UsuarioId", "Fecha" }, "IX_AUDITORIA_USUARIO_FECHA");

                    b.ToTable("AUDITORIA", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.CalificacionRecomendacion", b =>
                {
                    b.Property<int>("CalificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("calificacion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalificacionId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("RecomendacionId")
                        .HasColumnType("int")
                        .HasColumnName("recomendacion_id");

                    b.Property<int>("Valor")
                        .HasColumnType("int")
                        .HasColumnName("valor");

                    b.HasKey("CalificacionId");

                    b.HasIndex("ClienteId");

                    b.HasIndex(new[] { "RecomendacionId" }, "UQ_CALIFICACION_RECOMENDACION")
                        .IsUnique();

                    b.ToTable("CALIFICACION_RECOMENDACION", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.Cliente", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<string>("BadgeNumero")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("badge_numero");

                    b.Property<int?>("EntrenadorId")
                        .HasColumnType("int")
                        .HasColumnName("entrenador_id");

                    b.Property<string>("Nivel")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nivel");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("objetivo");

                    b.HasKey("UsuarioId");

                    b.HasIndex(new[] { "BadgeNumero" }, "IX_CLIENTE_BADGE");

                    b.HasIndex(new[] { "EntrenadorId" }, "IX_CLIENTE_ENTRENADOR");

                    b.HasIndex(new[] { "BadgeNumero" }, "UQ_CLIENTE_BADGE")
                        .IsUnique()
                        .HasFilter("[badge_numero] IS NOT NULL");

                    b.ToTable("CLIENTE", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.Ejercicio", b =>
                {
                    b.Property<int>("EjercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ejercicio_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EjercicioId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("GrupoMuscular")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("grupo_muscular");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.HasKey("EjercicioId");

                    b.ToTable("EJERCICIO", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.Entrenador", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("especialidad");

                    b.HasKey("UsuarioId");

                    b.ToTable("ENTRENADOR", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.EvaluacionFisica", b =>
                {
                    b.Property<int>("EvaluacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("evaluacion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluacionId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<int>("EntrenadorId")
                        .HasColumnType("int")
                        .HasColumnName("entrenador_id");

                    b.Property<decimal?>("Estatura")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("estatura");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Medidas")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("medidas");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("peso");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo");

                    b.HasKey("EvaluacionId");

                    b.HasIndex("EntrenadorId");

                    b.HasIndex(new[] { "ClienteId" }, "IX_EVALUACION_CLIENTE");

                    b.ToTable("EVALUACION_FISICA", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("evento_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventoId"));

                    b.Property<int>("AdministradorId")
                        .HasColumnType("int")
                        .HasColumnName("administrador_id");

                    b.Property<int>("CupoMaximo")
                        .HasColumnType("int")
                        .HasColumnName("cupo_maximo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("ACTIVO")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.HasKey("EventoId");

                    b.HasIndex("AdministradorId");

                    b.ToTable("EVENTO", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.HorarioTarea", b =>
                {
                    b.Property<int>("HorarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("horario_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HorarioId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("PENDIENTE")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Tarea")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tarea");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("HorarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HORARIO_TAREA", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.InscripcionEvento", b =>
                {
                    b.Property<int>("EventoId")
                        .HasColumnType("int")
                        .HasColumnName("evento_id");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("INSCRITO")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_inscripcion")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("EventoId", "ClienteId");

                    b.HasIndex("ClienteId");

                    b.ToTable("INSCRIPCION_EVENTO", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.Membresium", b =>
                {
                    b.Property<int>("MembresiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("membresia_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembresiaId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("ACTIVA")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.HasKey("MembresiaId");

                    b.HasIndex("PlanId");

                    b.HasIndex(new[] { "ClienteId" }, "IX_MEMBRESIA_CLIENTE");

                    b.ToTable("MEMBRESIA", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.Metum", b =>
                {
                    b.Property<int>("MetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("meta_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetaId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("ACTIVA")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateOnly?>("FechaLimite")
                        .HasColumnType("date")
                        .HasColumnName("fecha_limite");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tipo");

                    b.Property<decimal?>("ValorObjetivo")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valor_objetivo");

                    b.HasKey("MetaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("META", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.MultimediaEjercicio", b =>
                {
                    b.Property<int>("MultimediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("multimedia_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MultimediaId"));

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int")
                        .HasColumnName("ejercicio_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tipo");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("url");

                    b.HasKey("MultimediaId");

                    b.HasIndex("EjercicioId");

                    b.ToTable("MULTIMEDIA_EJERCICIO", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.Notificacion", b =>
                {
                    b.Property<int>("NotificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notificacion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacionId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("NO_LEIDA")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mensaje");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("NotificacionId");

                    b.HasIndex(new[] { "UsuarioId" }, "IX_NOTIFICACION_USUARIO");

                    b.ToTable("NOTIFICACION", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.ObservacionEntrenador", b =>
                {
                    b.Property<int>("ObservacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("observacion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObservacionId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contenido");

                    b.Property<int>("EntrenadorId")
                        .HasColumnType("int")
                        .HasColumnName("entrenador_id");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("ObservacionId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EntrenadorId");

                    b.ToTable("OBSERVACION_ENTRENADOR", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pago_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_pago")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("MembresiaId")
                        .HasColumnType("int")
                        .HasColumnName("membresia_id");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("monto");

                    b.Property<int>("RegistradoPor")
                        .HasColumnType("int")
                        .HasColumnName("registrado_por");

                    b.HasKey("PagoId");

                    b.HasIndex("RegistradoPor");

                    b.HasIndex(new[] { "MembresiaId" }, "IX_PAGO_MEMBRESIA");

                    b.ToTable("PAGO", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.ParametroRecomendacion", b =>
                {
                    b.Property<int>("ParametroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("parametro_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParametroId"));

                    b.Property<int>("AdministradorId")
                        .HasColumnType("int")
                        .HasColumnName("administrador_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("valor");

                    b.HasKey("ParametroId");

                    b.HasIndex("AdministradorId");

                    b.ToTable("PARAMETRO_RECOMENDACION", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.Permiso", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("permiso_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermisoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("PermisoId");

                    b.HasIndex(new[] { "Nombre" }, "UQ_PERMISO_NOMBRE")
                        .IsUnique();

                    b.ToTable("PERMISO", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.PlanMembresium", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<int>("DuracionMeses")
                        .HasColumnType("int")
                        .HasColumnName("duracion_meses");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio");

                    b.HasKey("PlanId");

                    b.ToTable("PLAN_MEMBRESIA", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.PrediccionDesercion", b =>
                {
                    b.Property<int>("PrediccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("prediccion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrediccionId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<decimal>("Confiabilidad")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("confiabilidad");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("NivelRiesgo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nivel_riesgo");

                    b.HasKey("PrediccionId");

                    b.HasIndex(new[] { "ClienteId" }, "IX_PREDICCION_CLIENTE");

                    b.ToTable("PREDICCION_DESERCION", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.Recomendacion", b =>
                {
                    b.Property<int>("RecomendacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("recomendacion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecomendacionId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<int?>("EntrenadorId")
                        .HasColumnType("int")
                        .HasColumnName("entrenador_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("PENDIENTE")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("RutinaSugeridaId")
                        .HasColumnType("int")
                        .HasColumnName("rutina_sugerida_id");

                    b.HasKey("RecomendacionId");

                    b.HasIndex("EntrenadorId");

                    b.HasIndex("RutinaSugeridaId");

                    b.HasIndex(new[] { "ClienteId" }, "IX_RECOMENDACION_CLIENTE");

                    b.ToTable("RECOMENDACION", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.Reporte", b =>
                {
                    b.Property<int>("ReporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reporte_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReporteId"));

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_generacion")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("FormatoExportado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("formato_exportado");

                    b.Property<int>("GeneradoPor")
                        .HasColumnType("int")
                        .HasColumnName("generado_por");

                    b.Property<DateOnly?>("PeriodoFin")
                        .HasColumnType("date")
                        .HasColumnName("periodo_fin");

                    b.Property<DateOnly?>("PeriodoInicio")
                        .HasColumnType("date")
                        .HasColumnName("periodo_inicio");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tipo");

                    b.HasKey("ReporteId");

                    b.HasIndex("GeneradoPor");

                    b.ToTable("REPORTE", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("RolId");

                    b.HasIndex(new[] { "Nombre" }, "UQ_ROL_NOMBRE")
                        .IsUnique();

                    b.ToTable("ROL", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.Rutina", b =>
                {
                    b.Property<int>("RutinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rutina_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RutinaId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<int>("EntrenadorId")
                        .HasColumnType("int")
                        .HasColumnName("entrenador_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("ACTIVA")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Nivel")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nivel");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("objetivo");

                    b.HasKey("RutinaId");

                    b.HasIndex(new[] { "EntrenadorId" }, "IX_RUTINA_ENTRENADOR");

                    b.ToTable("RUTINA", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.RutinaEjercicio", b =>
                {
                    b.Property<int>("RutinaId")
                        .HasColumnType("int")
                        .HasColumnName("rutina_id");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int")
                        .HasColumnName("ejercicio_id");

                    b.Property<int>("DescansoSegundos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60)
                        .HasColumnName("descanso_segundos");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("int")
                        .HasColumnName("repeticiones");

                    b.Property<int>("Series")
                        .HasColumnType("int")
                        .HasColumnName("series");

                    b.HasKey("RutinaId", "EjercicioId");

                    b.HasIndex("EjercicioId");

                    b.HasIndex(new[] { "RutinaId", "Orden" }, "UQ_RUTINA_EJERCICIO_ORDEN")
                        .IsUnique();

                    b.ToTable("RUTINA_EJERCICIO", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.SesionEjercicio", b =>
                {
                    b.Property<int>("SesionId")
                        .HasColumnType("int")
                        .HasColumnName("sesion_id");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int")
                        .HasColumnName("ejercicio_id");

                    b.Property<bool>("Completado")
                        .HasColumnType("bit")
                        .HasColumnName("completado");

                    b.Property<DateTime?>("FechaMarcado")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_marcado");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observaciones");

                    b.Property<decimal?>("PesoUtilizado")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("peso_utilizado");

                    b.Property<int?>("RepeticionesRealizadas")
                        .HasColumnType("int")
                        .HasColumnName("repeticiones_realizadas");

                    b.Property<int?>("SeriesCompletadas")
                        .HasColumnType("int")
                        .HasColumnName("series_completadas");

                    b.HasKey("SesionId", "EjercicioId");

                    b.HasIndex("EjercicioId");

                    b.ToTable("SESION_EJERCICIO", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.SesionEntrenamiento", b =>
                {
                    b.Property<int>("SesionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sesion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SesionId"));

                    b.Property<int>("AsignacionId")
                        .HasColumnType("int")
                        .HasColumnName("asignacion_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("EN_PROGRESO")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("SesionId");

                    b.HasIndex(new[] { "AsignacionId" }, "IX_SESION_ASIGNACION");

                    b.ToTable("SESION_ENTRENAMIENTO", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ACTIVO")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("FotoPerfil")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("foto_perfil");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("telefono");

                    b.HasKey("UsuarioId");

                    b.HasIndex(new[] { "RolId" }, "IX_USUARIO_ROL");

                    b.HasIndex(new[] { "Correo" }, "UQ_USUARIO_CORREO")
                        .IsUnique();

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.ValidacionPrediccion", b =>
                {
                    b.Property<int>("ValidacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("validacion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ValidacionId"));

                    b.Property<int>("AdministradorId")
                        .HasColumnType("int")
                        .HasColumnName("administrador_id");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("PrediccionId")
                        .HasColumnType("int")
                        .HasColumnName("prediccion_id");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("resultado");

                    b.HasKey("ValidacionId");

                    b.HasIndex("AdministradorId");

                    b.HasIndex(new[] { "PrediccionId" }, "UQ_VALIDACION_PREDICCION")
                        .IsUnique();

                    b.ToTable("VALIDACION_PREDICCION", (string)null);
                });

            modelBuilder.Entity("RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int")
                        .HasColumnName("permiso_id");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("ROL_PERMISO", (string)null);
                });

            modelBuilder.Entity("KROTraining.Models.Administrador", b =>
                {
                    b.HasOne("KROTraining.Models.Usuario", "Usuario")
                        .WithOne("Administrador")
                        .HasForeignKey("KROTraining.Models.Administrador", "UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_ADMINISTRADOR_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KROTraining.Models.AsignacionRutina", b =>
                {
                    b.HasOne("KROTraining.Models.Cliente", "Cliente")
                        .WithMany("AsignacionRutinas")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_ASIGNACION_CLIENTE");

                    b.HasOne("KROTraining.Models.Entrenador", "Entrenador")
                        .WithMany("AsignacionRutinas")
                        .HasForeignKey("EntrenadorId")
                        .IsRequired()
                        .HasConstraintName("FK_ASIGNACION_ENTRENADOR");

                    b.HasOne("KROTraining.Models.Rutina", "Rutina")
                        .WithMany("AsignacionRutinas")
                        .HasForeignKey("RutinaId")
                        .IsRequired()
                        .HasConstraintName("FK_ASIGNACION_RUTINA");

                    b.Navigation("Cliente");

                    b.Navigation("Entrenador");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("KROTraining.Models.Asistencium", b =>
                {
                    b.HasOne("KROTraining.Models.Cliente", "Cliente")
                        .WithMany("Asistencia")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_ASISTENCIA_CLIENTE");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("KROTraining.Models.Auditorium", b =>
                {
                    b.HasOne("KROTraining.Models.Usuario", "Usuario")
                        .WithMany("Auditoria")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_AUDITORIA_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KROTraining.Models.CalificacionRecomendacion", b =>
                {
                    b.HasOne("KROTraining.Models.Cliente", "Cliente")
                        .WithMany("CalificacionRecomendacions")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_CALIFICACION_CLIENTE");

                    b.HasOne("KROTraining.Models.Recomendacion", "Recomendacion")
                        .WithOne("CalificacionRecomendacion")
                        .HasForeignKey("KROTraining.Models.CalificacionRecomendacion", "RecomendacionId")
                        .IsRequired()
                        .HasConstraintName("FK_CALIFICACION_RECOMENDACION");

                    b.Navigation("Cliente");

                    b.Navigation("Recomendacion");
                });

            modelBuilder.Entity("KROTraining.Models.Cliente", b =>
                {
                    b.HasOne("KROTraining.Models.Entrenador", "Entrenador")
                        .WithMany("Clientes")
                        .HasForeignKey("EntrenadorId")
                        .HasConstraintName("FK_CLIENTE_ENTRENADOR");

                    b.HasOne("KROTraining.Models.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("KROTraining.Models.Cliente", "UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_CLIENTE_USUARIO");

                    b.Navigation("Entrenador");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KROTraining.Models.Entrenador", b =>
                {
                    b.HasOne("KROTraining.Models.Usuario", "Usuario")
                        .WithOne("Entrenador")
                        .HasForeignKey("KROTraining.Models.Entrenador", "UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_ENTRENADOR_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KROTraining.Models.EvaluacionFisica", b =>
                {
                    b.HasOne("KROTraining.Models.Cliente", "Cliente")
                        .WithMany("EvaluacionFisicas")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_EVALUACION_CLIENTE");

                    b.HasOne("KROTraining.Models.Entrenador", "Entrenador")
                        .WithMany("EvaluacionFisicas")
                        .HasForeignKey("EntrenadorId")
                        .IsRequired()
                        .HasConstraintName("FK_EVALUACION_ENTRENADOR");

                    b.Navigation("Cliente");

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("KROTraining.Models.Evento", b =>
                {
                    b.HasOne("KROTraining.Models.Administrador", "Administrador")
                        .WithMany("Eventos")
                        .HasForeignKey("AdministradorId")
                        .IsRequired()
                        .HasConstraintName("FK_EVENTO_ADMINISTRADOR");

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("KROTraining.Models.HorarioTarea", b =>
                {
                    b.HasOne("KROTraining.Models.Usuario", "Usuario")
                        .WithMany("HorarioTareas")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_HORARIO_TAREA_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KROTraining.Models.InscripcionEvento", b =>
                {
                    b.HasOne("KROTraining.Models.Cliente", "Cliente")
                        .WithMany("InscripcionEventos")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_INSCRIPCION_CLIENTE");

                    b.HasOne("KROTraining.Models.Evento", "Evento")
                        .WithMany("InscripcionEventos")
                        .HasForeignKey("EventoId")
                        .IsRequired()
                        .HasConstraintName("FK_INSCRIPCION_EVENTO");

                    b.Navigation("Cliente");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("KROTraining.Models.Membresium", b =>
                {
                    b.HasOne("KROTraining.Models.Cliente", "Cliente")
                        .WithMany("Membresia")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_MEMBRESIA_CLIENTE");

                    b.HasOne("KROTraining.Models.PlanMembresium", "Plan")
                        .WithMany("Membresia")
                        .HasForeignKey("PlanId")
                        .IsRequired()
                        .HasConstraintName("FK_MEMBRESIA_PLAN");

                    b.Navigation("Cliente");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("KROTraining.Models.Metum", b =>
                {
                    b.HasOne("KROTraining.Models.Cliente", "Cliente")
                        .WithMany("Meta")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_META_CLIENTE");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("KROTraining.Models.MultimediaEjercicio", b =>
                {
                    b.HasOne("KROTraining.Models.Ejercicio", "Ejercicio")
                        .WithMany("MultimediaEjercicios")
                        .HasForeignKey("EjercicioId")
                        .IsRequired()
                        .HasConstraintName("FK_MULTIMEDIA_EJERCICIO");

                    b.Navigation("Ejercicio");
                });

            modelBuilder.Entity("KROTraining.Models.Notificacion", b =>
                {
                    b.HasOne("KROTraining.Models.Usuario", "Usuario")
                        .WithMany("Notificacions")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_NOTIFICACION_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KROTraining.Models.ObservacionEntrenador", b =>
                {
                    b.HasOne("KROTraining.Models.Cliente", "Cliente")
                        .WithMany("ObservacionEntrenadors")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_OBSERVACION_CLIENTE");

                    b.HasOne("KROTraining.Models.Entrenador", "Entrenador")
                        .WithMany("ObservacionEntrenadors")
                        .HasForeignKey("EntrenadorId")
                        .IsRequired()
                        .HasConstraintName("FK_OBSERVACION_ENTRENADOR");

                    b.Navigation("Cliente");

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("KROTraining.Models.Pago", b =>
                {
                    b.HasOne("KROTraining.Models.Membresium", "Membresia")
                        .WithMany("Pagos")
                        .HasForeignKey("MembresiaId")
                        .IsRequired()
                        .HasConstraintName("FK_PAGO_MEMBRESIA");

                    b.HasOne("KROTraining.Models.Usuario", "RegistradoPorNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("RegistradoPor")
                        .IsRequired()
                        .HasConstraintName("FK_PAGO_USUARIO");

                    b.Navigation("Membresia");

                    b.Navigation("RegistradoPorNavigation");
                });

            modelBuilder.Entity("KROTraining.Models.ParametroRecomendacion", b =>
                {
                    b.HasOne("KROTraining.Models.Administrador", "Administrador")
                        .WithMany("ParametroRecomendacions")
                        .HasForeignKey("AdministradorId")
                        .IsRequired()
                        .HasConstraintName("FK_PARAMETRO_ADMINISTRADOR");

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("KROTraining.Models.PrediccionDesercion", b =>
                {
                    b.HasOne("KROTraining.Models.Cliente", "Cliente")
                        .WithMany("PrediccionDesercions")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_PREDICCION_CLIENTE");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("KROTraining.Models.Recomendacion", b =>
                {
                    b.HasOne("KROTraining.Models.Cliente", "Cliente")
                        .WithMany("Recomendacions")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_RECOMENDACION_CLIENTE");

                    b.HasOne("KROTraining.Models.Entrenador", "Entrenador")
                        .WithMany("Recomendacions")
                        .HasForeignKey("EntrenadorId")
                        .HasConstraintName("FK_RECOMENDACION_ENTRENADOR");

                    b.HasOne("KROTraining.Models.Rutina", "RutinaSugerida")
                        .WithMany("Recomendacions")
                        .HasForeignKey("RutinaSugeridaId")
                        .IsRequired()
                        .HasConstraintName("FK_RECOMENDACION_RUTINA");

                    b.Navigation("Cliente");

                    b.Navigation("Entrenador");

                    b.Navigation("RutinaSugerida");
                });

            modelBuilder.Entity("KROTraining.Models.Reporte", b =>
                {
                    b.HasOne("KROTraining.Models.Usuario", "GeneradoPorNavigation")
                        .WithMany("Reportes")
                        .HasForeignKey("GeneradoPor")
                        .IsRequired()
                        .HasConstraintName("FK_REPORTE_USUARIO");

                    b.Navigation("GeneradoPorNavigation");
                });

            modelBuilder.Entity("KROTraining.Models.Rutina", b =>
                {
                    b.HasOne("KROTraining.Models.Entrenador", "Entrenador")
                        .WithMany("Rutinas")
                        .HasForeignKey("EntrenadorId")
                        .IsRequired()
                        .HasConstraintName("FK_RUTINA_ENTRENADOR");

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("KROTraining.Models.RutinaEjercicio", b =>
                {
                    b.HasOne("KROTraining.Models.Ejercicio", "Ejercicio")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("EjercicioId")
                        .IsRequired()
                        .HasConstraintName("FK_RUTINA_EJERCICIO_EJERCICIO");

                    b.HasOne("KROTraining.Models.Rutina", "Rutina")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("RutinaId")
                        .IsRequired()
                        .HasConstraintName("FK_RUTINA_EJERCICIO_RUTINA");

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("KROTraining.Models.SesionEjercicio", b =>
                {
                    b.HasOne("KROTraining.Models.Ejercicio", "Ejercicio")
                        .WithMany("SesionEjercicios")
                        .HasForeignKey("EjercicioId")
                        .IsRequired()
                        .HasConstraintName("FK_SESION_EJERCICIO_EJERCICIO");

                    b.HasOne("KROTraining.Models.SesionEntrenamiento", "Sesion")
                        .WithMany("SesionEjercicios")
                        .HasForeignKey("SesionId")
                        .IsRequired()
                        .HasConstraintName("FK_SESION_EJERCICIO_SESION");

                    b.Navigation("Ejercicio");

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("KROTraining.Models.SesionEntrenamiento", b =>
                {
                    b.HasOne("KROTraining.Models.AsignacionRutina", "Asignacion")
                        .WithMany("SesionEntrenamientos")
                        .HasForeignKey("AsignacionId")
                        .IsRequired()
                        .HasConstraintName("FK_SESION_ASIGNACION");

                    b.Navigation("Asignacion");
                });

            modelBuilder.Entity("KROTraining.Models.Usuario", b =>
                {
                    b.HasOne("KROTraining.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_USUARIO_ROL");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("KROTraining.Models.ValidacionPrediccion", b =>
                {
                    b.HasOne("KROTraining.Models.Administrador", "Administrador")
                        .WithMany("ValidacionPrediccions")
                        .HasForeignKey("AdministradorId")
                        .IsRequired()
                        .HasConstraintName("FK_VALIDACION_ADMINISTRADOR");

                    b.HasOne("KROTraining.Models.PrediccionDesercion", "Prediccion")
                        .WithOne("ValidacionPrediccion")
                        .HasForeignKey("KROTraining.Models.ValidacionPrediccion", "PrediccionId")
                        .IsRequired()
                        .HasConstraintName("FK_VALIDACION_PREDICCION");

                    b.Navigation("Administrador");

                    b.Navigation("Prediccion");
                });

            modelBuilder.Entity("RolPermiso", b =>
                {
                    b.HasOne("KROTraining.Models.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .IsRequired()
                        .HasConstraintName("FK_ROL_PERMISO_PERMISO");

                    b.HasOne("KROTraining.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_ROL_PERMISO_ROL");
                });

            modelBuilder.Entity("KROTraining.Models.Administrador", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("ParametroRecomendacions");

                    b.Navigation("ValidacionPrediccions");
                });

            modelBuilder.Entity("KROTraining.Models.AsignacionRutina", b =>
                {
                    b.Navigation("SesionEntrenamientos");
                });

            modelBuilder.Entity("KROTraining.Models.Cliente", b =>
                {
                    b.Navigation("AsignacionRutinas");

                    b.Navigation("Asistencia");

                    b.Navigation("CalificacionRecomendacions");

                    b.Navigation("EvaluacionFisicas");

                    b.Navigation("InscripcionEventos");

                    b.Navigation("Membresia");

                    b.Navigation("Meta");

                    b.Navigation("ObservacionEntrenadors");

                    b.Navigation("PrediccionDesercions");

                    b.Navigation("Recomendacions");
                });

            modelBuilder.Entity("KROTraining.Models.Ejercicio", b =>
                {
                    b.Navigation("MultimediaEjercicios");

                    b.Navigation("RutinaEjercicios");

                    b.Navigation("SesionEjercicios");
                });

            modelBuilder.Entity("KROTraining.Models.Entrenador", b =>
                {
                    b.Navigation("AsignacionRutinas");

                    b.Navigation("Clientes");

                    b.Navigation("EvaluacionFisicas");

                    b.Navigation("ObservacionEntrenadors");

                    b.Navigation("Recomendacions");

                    b.Navigation("Rutinas");
                });

            modelBuilder.Entity("KROTraining.Models.Evento", b =>
                {
                    b.Navigation("InscripcionEventos");
                });

            modelBuilder.Entity("KROTraining.Models.Membresium", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("KROTraining.Models.PlanMembresium", b =>
                {
                    b.Navigation("Membresia");
                });

            modelBuilder.Entity("KROTraining.Models.PrediccionDesercion", b =>
                {
                    b.Navigation("ValidacionPrediccion");
                });

            modelBuilder.Entity("KROTraining.Models.Recomendacion", b =>
                {
                    b.Navigation("CalificacionRecomendacion");
                });

            modelBuilder.Entity("KROTraining.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("KROTraining.Models.Rutina", b =>
                {
                    b.Navigation("AsignacionRutinas");

                    b.Navigation("Recomendacions");

                    b.Navigation("RutinaEjercicios");
                });

            modelBuilder.Entity("KROTraining.Models.SesionEntrenamiento", b =>
                {
                    b.Navigation("SesionEjercicios");
                });

            modelBuilder.Entity("KROTraining.Models.Usuario", b =>
                {
                    b.Navigation("Administrador");

                    b.Navigation("Auditoria");

                    b.Navigation("Cliente");

                    b.Navigation("Entrenador");

                    b.Navigation("HorarioTareas");

                    b.Navigation("Notificacions");

                    b.Navigation("Pagos");

                    b.Navigation("Reportes");
                });
#pragma warning restore 612, 618
        }
    }
}
